# Full AICMS validation workflow with breaking change detection
# Copy this file to .github/workflows/aicms.yml in your project

name: AICMS Validation

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  lint:
    name: Lint Annotations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: AICMS Lint
        id: aicms
        uses: aicms/check@v1
        with:
          path: 'src/'
          require-intent: 'true'
          require-module-intent: 'true'
          warn-low-confidence: 'true'
          confidence-threshold: '0.7'
          output-format: 'text'

      - name: Comment on PR (if errors)
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## AICMS Validation Failed

            **Errors:** ${{ steps.aicms.outputs.errors }}
            **Warnings:** ${{ steps.aicms.outputs.warnings }}

            Please ensure all functions have \`@ai:intent\` annotations.
            See the [AICMS documentation](https://github.com/your-org/aicms) for details.`
            })

  breaking-changes:
    name: Check Breaking Changes
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for diff

      - name: AICMS Breaking Change Check
        uses: aicms/check@v1
        with:
          check-breaking-changes: 'true'
          base-branch: ${{ github.base_ref }}

      - name: Comment Breaking Changes on PR
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## ⚠️ Breaking Contract Changes Detected

            This PR contains breaking changes to function contracts:
            - Preconditions may have been strengthened
            - Postconditions may have been weakened
            - Side effects may have been expanded

            Please review the changes and update the PR description with migration notes if needed.`
            })
